
vec3	path_trace(vec3 ro, vec3 rd)
{
	vec3		accumulation = vec3(0.0);
	vec3		power = vec3(1.0);
	int			depth = 0;
	hit_record	hit;

	hit.t = IT_MAX;
	while (depth < max_bounces)
	{
		hit.t = IT_MAX; 
		if (hit_register_all(hit, ro, rd, true) == true)
		{
			ro = hit.point;
			material_manager_v4(ro, rd, hit, power, accumulation);
		}
		else
		{
			accumulation = add_skybox(rd, power, accumulation);
			break ;
		}
		depth++;
	}
	return (accumulation);
}